// frontend-react/src/components/overview/MetricCard.tsx
import React from 'react'
import { Card, Progress } from 'antd'

interface MetricCardProps {
  value: number
  title: string
  extraValues?: string
  isProgress?: boolean
}

const MetricCard: React.FC<MetricCardProps> = ({
  value,
  title,
  extraValues,
  isProgress = false,
}) => {
  const getProgressColor = (percentage: number) => {
    if (percentage >= 90) return '#f5222d'
    if (percentage >= 80) return '#fa8c16'
    if (percentage >= 60) return '#52c41a'
    if (percentage >= 40) return '#1890ff'
    return '#722ed1'
  }

  return (
    <Card className="flex-1 min-w-64">
      <div className="text-center">
        {isProgress ? (
          <div className="mb-4">
            <Progress
              type="dashboard"
              percent={Number(value.toFixed(2))}
              strokeColor={getProgressColor(value)}
              format={(percent) => `${percent}%`}
            />
          </div>
        ) : (
          <div className="h-36 flex items-center justify-center">
            <span className="text-3xl font-bold">{value}</span>
          </div>
        )}
        <div className="text-lg font-bold mb-1">{title}</div>
        {extraValues && (
          <div className="text-sm text-gray-500">{extraValues}</div>
        )}
      </div>
    </Card>
  )
}

export default MetricCard

// frontend/components/pages/overview/MetricCard.vue
<script setup lang="ts">
import { type ProgressFn } from "element-plus";

interface Props {
  value: number;
  title: string;
  extraValues?: string;
  isProgress?: boolean;
}

const {
  value,
  title,
  extraValues = "",
  isProgress = false,
} = defineProps<Props>();

const progressBarColors = [
  { color: "#f56c6c", percentage: 100 },
  { color: "#e6a23c", percentage: 80 },
  { color: "#5cb87a", percentage: 60 },
  { color: "#1989fa", percentage: 40 },
  { color: "#6f7ad3", percentage: 20 },
];

const progressBarPercentageFormatter: ProgressFn = (percentage: number) => {
  return percentage.toFixed(2) + "%";
};
</script>

<template>
  <ElCard class="metric-item flex-1">
    <div class="flex flex-col items-center">
      <div v-if="isProgress">
        <ElProgress
          type="dashboard"
          :percentage="value"
          :format="progressBarPercentageFormatter"
          :color="progressBarColors"
        />
      </div>
      <div v-else class="metric-value h-36 flex justify-center items-center">
        <p class="text-2xl font-bold">{{ value }}</p>
      </div>
      <div class="metric-title text-lg font-bold">{{ title }}</div>
      <div v-if="extraValues" class="metric-value">
        {{ extraValues }}
      </div>
    </div>
  </ElCard>
</template>

<style lang="scss" scoped></style>
